local imperial = {
  config = {
    name = "Kalendarz imperialny",
    domain = "imperial",
    days_in_year = 400,
    first_day_of_calparts = {
      ["Hexentag"] = 1,
      ["Nachhexen"] = 2,
      ["Jahrdrung"] = 34,
      ["Mitterfruhl"] = 67,
      ["Pflugzeit"] = 68,
      ["Sigmarszeit"] = 101,
      ["Sommerzeit"] = 134,
      ["Sonnenstill"] = 167,
      ["Vorgeheim"] = 168,
      ["Geheimnistag"] = 201,
      ["Nachgeheim"] = 202,
      ["Erntezeit"] = 234,
      ["Mitterherbst"] = 267,
      ["Brauzeit"] = 268,
      ["Kaltezeit"] = 301,
      ["Ulrichszeit"] = 334,
      ["Mondstill"] = 367,
      ["Vorhexen"] = 368,
    },
    seasons = {
      { day = 1, name = "Pozna zima" },
      { day = 18, name = "Wczesna wiosna" },
      { day = 67, name = "Pozna wiosna" },
      { day = 118, name = "Wczesne lato" },
      { day = 167, name = "Pozne lato" },
      { day = 218, name = "Wczesna jesien" },
      { day = 267, name = "Pozna jesien" },
      { day = 319, name = "Wczesna zima" },
    },
    sun_cycle = {
      { day = 18, sunrise = "06:30", sunset = "18:30" },
      { day = 118, sunrise = "05:00", sunset = "21:00" },
      { day = 218, sunrise = "06:30", sunset = "18:30" },
      { day = 319, sunrise = "08:00", sunset = "17:00" },
    },
    search_times = {
      { day = 1, hour = 17, desc = "Leci pyl", color = "dodger_blue", type = "special_imperial" },
      { day = 1, hour = 17, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 2, hour = 8, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 14, hour = 17, desc = "Poczatek nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 15, hour = 8, desc = "Koniec nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 26, hour = 17, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 27, hour = 8, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 39, hour = 18, desc = "Poczatek nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 40, hour = 7, desc = "Koniec nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 51, hour = 18, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 52, hour = 7, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 64, hour = 18, desc = "Poczatek nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 65, hour = 7, desc = "Koniec nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 76, hour = 19, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 77, hour = 6, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 89, hour = 19, desc = "Poczatek nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 90, hour = 6, desc = "Koniec nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 102, hour = 21, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 103, hour = 5, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 114, hour = 20, desc = "Poczatek nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 115, hour = 5, desc = "Koniec nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 126, hour = 20, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 127, hour = 5, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 139, hour = 21, desc = "Poczatek nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 140, hour = 5, desc = "Koniec nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 151, hour = 21, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 152, hour = 5, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 164, hour = 21, desc = "Poczatek nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 165, hour = 5, desc = "Koniec nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 176, hour = 22, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 177, hour = 4, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 189, hour = 22, desc = "Poczatek nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 190, hour = 4, desc = "Koniec nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 201, hour = 17, desc = "Leci pyl", color = "dodger_blue", type = "special_imperial" },
      { day = 202, hour = 20, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 203, hour = 5, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 214, hour = 20, desc = "Poczatek nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 215, hour = 5, desc = "Koniec nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 227, hour = 20, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 228, hour = 5, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 239, hour = 20, desc = "Poczatek nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 240, hour = 5, desc = "Koniec nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 251, hour = 20, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 252, hour = 5, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 253, hour = 20, desc = "Leci pyl", color = "dodger_blue", type = "special_imperial" },
      { day = 264, hour = 20, desc = "Poczatek nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 265, hour = 5, desc = "Koniec nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 276, hour = 19, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 277, hour = 6, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 278, hour = 19, desc = "Leci pyl", color = "dodger_blue", type = "special_imperial" },
      { day = 289, hour = 19, desc = "Poczatek nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 290, hour = 6, desc = "Koniec nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 301, hour = 18, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 302, hour = 6, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 314, hour = 18, desc = "Poczatek nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 315, hour = 6, desc = "Koniec nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 326, hour = 18, desc = "Leci pyl", color = "dodger_blue", type = "special_imperial" },
      { day = 326, hour = 18, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 327, hour = 6, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 339, hour = 17, desc = "Poczatek nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 340, hour = 7, desc = "Koniec nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 351, hour = 17, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 352, hour = 7, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 364, hour = 17, desc = "Poczatek nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 365, hour = 7, desc = "Koniec nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 376, hour = 16, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 377, hour = 8, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_imperial" },
      { day = 389, hour = 16, desc = "Poczatek nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 390, hour = 8, desc = "Koniec nowiu", color = "slate_blue", type = "new_moon_imperial" },
      { day = 18, hour = 0, desc = "Poczatek wiosny", color = "green", type = "season_imperial" },
      { day = 118, hour = 0, desc = "Poczatek lata", color = "yellow", type = "season_imperial" },
      { day = 218, hour = 0, desc = "Poczatek jesieni", color = "brown", type = "season_imperial" },
      { day = 319, hour = 0, desc = "Poczatek zimy", color = "white", type = "season_imperial" },
    },
  },
  data = { offset = 0, precision = 119, results = {} },
}

return imperial
