local ishtar = {
  config = {
    name = "Kalendarz ishtar",
    domain = "ishtar",
    days_in_year = 360,
    first_day_of_calparts = {
      ["Yule"] = 1,
      ["Imbaelk"] = 46,
      ["Birke"] = 91,
      ["Blathe"] = 136,
      ["Feainn"] = 181,
      ["Lammas"] = 226,
      ["Velen"] = 271,
      ["Saovine"] = 316,
    },
    seasons = {
      { day = 1, name = "Zima" },
      { day = 91, name = "Wiosna" },
      { day = 181, name = "Lato" },
      { day = 271, name = "Jesien" },
    },
    sun_cycle = {
      { day = 1, sunrise = "08:00", sunset = "17:00" },
      { day = 91, sunrise = "06:30", sunset = "18:30" },
      { day = 181, sunrise = "05:00", sunset = "21:00" },
      { day = 271, sunrise = "06:30", sunset = "18:30" },
    },
    search_times = {
      { day = 1, hour = 0, desc = "Poczatek zimy", color = "white", type = "season_ishtar" },
      { day = 1, hour = 0, desc = "Przesilenie zimowe", color = "white", type = "solstice_ishtar" },
      { day = 1, hour = 0, desc = "Ryboludzie", color = "white", type = "fishman_ishtar" },
      { day = 6, hour = 5, desc = "Eysenlaan festyn", color = "magenta", type = "eys_feast_ishtar" },
      { day = 9, hour = 23, desc = "Eysenlaan koniec", color = "magenta", type = "eys_feast_ishtar" },
      { day = 4, hour = 0, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 6, hour = 0, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 4, hour = 2, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 4, hour = 8, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 7, hour = 22, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 8, hour = 8, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 28, hour = 0, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 30, hour = 0, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 28, hour = 2, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 28, hour = 8, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 31, hour = 22, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 32, hour = 8, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 51, hour = 5, desc = "Eysenlaan festyn", color = "magenta", type = "eys_feast_ishtar" },
      { day = 54, hour = 23, desc = "Eysenlaan koniec", color = "magenta", type = "eys_feast_ishtar" },
      { day = 52, hour = 0, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 54, hour = 0, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 52, hour = 2, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 52, hour = 7, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 55, hour = 22, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 56, hour = 7, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 76, hour = 0, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 78, hour = 0, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 76, hour = 2, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 76, hour = 7, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 79, hour = 22, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 80, hour = 7, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 91, hour = 0, desc = "Poczatek wiosny", color = "green", type = "season_ishtar" },
      { day = 91, hour = 0, desc = "Rownonoc wiosenna", color = "green", type = "equinox_ishtar" },
      { day = 91, hour = 0, desc = "Ryboludzie", color = "green", type = "fishman_ishtar" },
      { day = 96, hour = 5, desc = "Eysenlaan festyn", color = "magenta", type = "eys_feast_ishtar" },
      { day = 99, hour = 23, desc = "Eysenlaan koniec", color = "magenta", type = "eys_feast_ishtar" },
      { day = 100, hour = 0, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 102, hour = 0, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 100, hour = 2, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 100, hour = 6, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 103, hour = 22, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 104, hour = 6, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 124, hour = 0, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 126, hour = 0, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 124, hour = 2, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 124, hour = 6, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 127, hour = 22, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 128, hour = 6, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 141, hour = 5, desc = "Eysenlaan festyn", color = "magenta", type = "eys_feast_ishtar" },
      { day = 144, hour = 23, desc = "Eysenlaan koniec", color = "magenta", type = "eys_feast_ishtar" },
      { day = 148, hour = 0, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 150, hour = 0, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 148, hour = 2, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 148, hour = 5, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 151, hour = 22, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 152, hour = 5, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 172, hour = 0, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 174, hour = 0, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 172, hour = 2, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 172, hour = 5, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 175, hour = 22, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 176, hour = 5, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 181, hour = 0, desc = "Poczatek lata", color = "yellow", type = "season_ishtar" },
      { day = 181, hour = 0, desc = "Przesilenie letnie", color = "yellow", type = "solstice_ishtar" },
      { day = 181, hour = 0, desc = "Ryboludzie", color = "yellow", type = "fishman_ishtar" },
      { day = 186, hour = 5, desc = "Eysenlaan festyn", color = "magenta", type = "eys_feast_ishtar" },
      { day = 189, hour = 23, desc = "Eysenlaan koniec", color = "magenta", type = "eys_feast_ishtar" },
      { day = 196, hour = 0, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 198, hour = 0, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 196, hour = 2, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 196, hour = 4, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 199, hour = 22, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 200, hour = 4, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 220, hour = 0, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 224, hour = 0, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 220, hour = 2, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 220, hour = 4, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 225, hour = 22, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 226, hour = 5, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 231, hour = 5, desc = "Eysenlaan festyn", color = "magenta", type = "eys_feast_ishtar" },
      { day = 234, hour = 23, desc = "Eysenlaan koniec", color = "magenta", type = "eys_feast_ishtar" },
      { day = 244, hour = 0, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 246, hour = 0, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 244, hour = 2, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 244, hour = 5, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 247, hour = 22, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 248, hour = 5, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 268, hour = 0, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 270, hour = 0, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 268, hour = 2, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 268, hour = 5, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 271, hour = 0, desc = "Poczatek jesieni", color = "brown", type = "season_ishtar" },
      { day = 271, hour = 0, desc = "Rownonoc jesienna", color = "brown", type = "equinox_ishtar" },
      { day = 271, hour = 0, desc = "Ryboludzie", color = "brown", type = "fishman_ishtar" },
      { day = 271, hour = 22, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 272, hour = 7, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 276, hour = 5, desc = "Eysenlaan festyn", color = "magenta", type = "eys_feast_ishtar" },
      { day = 279, hour = 23, desc = "Eysenlaan koniec", color = "magenta", type = "eys_feast_ishtar" },
      { day = 292, hour = 0, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 294, hour = 0, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 292, hour = 2, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 292, hour = 7, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 295, hour = 22, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 296, hour = 7, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 315, hour = 18, desc = "Leci pyl", color = "dodger_blue", type = "special_ishtar" },
      { day = 316, hour = 0, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 318, hour = 0, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 316, hour = 2, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 316, hour = 6, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 319, hour = 22, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 320, hour = 6, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 321, hour = 5, desc = "Eysenlaan festyn", color = "magenta", type = "eys_feast_ishtar" },
      { day = 324, hour = 23, desc = "Eysenlaan koniec", color = "magenta", type = "eys_feast_ishtar" },
      { day = 340, hour = 0, desc = "Poczatek pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 342, hour = 0, desc = "Koniec pelni", color = "powder_blue", type = "full_moon_ishtar" },
      { day = 340, hour = 2, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 340, hour = 6, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
      { day = 343, hour = 22, desc = "Szpiedzy wychodza", color = "chocolate", type = "spy_ishtar" },
      { day = 344, hour = 6, desc = "Szpiedzy znikaja", color = "chocolate", type = "spy_ishtar" },
    },
  },
  data = { offset = 0, precision = 119, results = {} },
}

return ishtar
